-- Alterar constraint para aceitar mais tipos de layout
ALTER TABLE vv_b_modelos_boleto DROP CONSTRAINT IF EXISTS vv_b_modelos_boleto_tipo_layout_check;

ALTER TABLE vv_b_modelos_boleto ADD CONSTRAINT vv_b_modelos_boleto_tipo_layout_check 
  CHECK (tipo_layout = ANY (ARRAY['CNAB_240'::text, 'CNAB_400'::text, 'PDF'::text, 'UNIVERSAL'::text]));

-- Inserir modelo padrão de boleto Universal
INSERT INTO vv_b_modelos_boleto (
  id,
  nome_modelo,
  banco_id,
  bancos_compativeis,
  tipo_layout,
  formato_pagina,
  largura_pagina,
  altura_pagina,
  padrao,
  campos_mapeados,
  texto_instrucoes,
  pdf_storage_bucket,
  pdf_storage_path
) VALUES (
  'a0000000-0000-0000-0000-000000000001',
  'Modelo Padrão FEBRABAN',
  NULL,
  NULL,
  'UNIVERSAL',
  'A4',
  210,
  297,
  true,
  '[
    {"id":"hdr_banco_codigo","tipo":"banco_codigo","label":"Código Banco","variavel":"{{banco_codigo}}","x":15,"y":15,"largura":25,"altura":12,"fonte":"helvetica","tamanho_fonte":16,"negrito":true,"borda":true,"alinhamento":"center"},
    {"id":"hdr_banco_nome","tipo":"banco_nome","label":"Nome Banco","variavel":"{{banco_nome}}","x":40,"y":15,"largura":75,"altura":12,"fonte":"helvetica","tamanho_fonte":12,"negrito":true,"borda":true,"alinhamento":"center"},
    {"id":"hdr_linha_digitavel","tipo":"linha_digitavel","label":"Linha Digitável","variavel":"{{linha_digitavel}}","x":115,"y":15,"largura":80,"altura":12,"fonte":"courier","tamanho_fonte":10,"negrito":true,"borda":true,"alinhamento":"right"},
    {"id":"local_pgto_label","tipo":"custom","label":"Local de Pagamento","valor_fixo":"Local de Pagamento","x":15,"y":30,"largura":140,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"local_pagamento","tipo":"local_pagamento","label":"","variavel":"{{local_pagamento}}","x":15,"y":35,"largura":140,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true},
    {"id":"venc_label","tipo":"custom","label":"Vencimento","valor_fixo":"Vencimento","x":155,"y":30,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"data_vencimento","tipo":"data_vencimento","label":"","variavel":"{{data_vencimento}}","x":155,"y":35,"largura":40,"altura":8,"fonte":"helvetica","tamanho_fonte":10,"negrito":true,"borda":true,"alinhamento":"right","formato":"data"},
    {"id":"benef_label","tipo":"custom","label":"Beneficiário","valor_fixo":"Beneficiário","x":15,"y":45,"largura":105,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"beneficiario_nome","tipo":"beneficiario_nome","label":"","variavel":"{{beneficiario_nome}}","x":15,"y":50,"largura":105,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"negrito":true,"borda":true},
    {"id":"ag_cod_label","tipo":"custom","label":"Agência/Código Beneficiário","valor_fixo":"Agência/Código Beneficiário","x":120,"y":45,"largura":75,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"agencia_codigo","tipo":"agencia_codigo","label":"","variavel":"{{agencia_codigo}}","x":120,"y":50,"largura":75,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"alinhamento":"right"},
    {"id":"dt_doc_label","tipo":"custom","label":"Data do Documento","valor_fixo":"Data do Documento","x":15,"y":60,"largura":30,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"data_documento","tipo":"data_documento","label":"","variavel":"{{data_emissao}}","x":15,"y":65,"largura":30,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"formato":"data"},
    {"id":"num_doc_label","tipo":"custom","label":"Número do Documento","valor_fixo":"Número do Documento","x":45,"y":60,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"numero_documento","tipo":"numero_documento","label":"","variavel":"{{numero_documento}}","x":45,"y":65,"largura":40,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true},
    {"id":"esp_doc_label","tipo":"custom","label":"Espécie Doc.","valor_fixo":"Espécie Doc.","x":85,"y":60,"largura":20,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"especie_documento","tipo":"especie_documento","label":"","valor_fixo":"DM","x":85,"y":65,"largura":20,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"alinhamento":"center"},
    {"id":"aceite_label","tipo":"custom","label":"Aceite","valor_fixo":"Aceite","x":105,"y":60,"largura":15,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"aceite","tipo":"aceite","label":"","valor_fixo":"N","x":105,"y":65,"largura":15,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"alinhamento":"center"},
    {"id":"dt_proc_label","tipo":"custom","label":"Data Processamento","valor_fixo":"Data Processamento","x":120,"y":60,"largura":35,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"data_processamento","tipo":"data_processamento","label":"","variavel":"{{data_processamento}}","x":120,"y":65,"largura":35,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"formato":"data"},
    {"id":"nosso_num_label","tipo":"custom","label":"Nosso Número","valor_fixo":"Nosso Número","x":155,"y":60,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"nosso_numero","tipo":"nosso_numero","label":"","variavel":"{{nosso_numero}}","x":155,"y":65,"largura":40,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"negrito":true,"borda":true,"alinhamento":"right"},
    {"id":"uso_banco_label","tipo":"custom","label":"Uso do Banco","valor_fixo":"Uso do Banco","x":15,"y":75,"largura":20,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"uso_banco","tipo":"custom","label":"","x":15,"y":80,"largura":20,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true},
    {"id":"carteira_label","tipo":"custom","label":"Carteira","valor_fixo":"Carteira","x":35,"y":75,"largura":25,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"carteira","tipo":"carteira","label":"","variavel":"{{carteira}}","x":35,"y":80,"largura":25,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"alinhamento":"center"},
    {"id":"especie_label","tipo":"custom","label":"Espécie","valor_fixo":"Espécie","x":60,"y":75,"largura":20,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"especie_moeda","tipo":"especie_moeda","label":"","valor_fixo":"R$","x":60,"y":80,"largura":20,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"alinhamento":"center"},
    {"id":"quantidade_label","tipo":"custom","label":"Quantidade","valor_fixo":"Quantidade","x":80,"y":75,"largura":30,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"quantidade","tipo":"quantidade","label":"","variavel":"{{quantidade}}","x":80,"y":80,"largura":30,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true},
    {"id":"valor_label","tipo":"custom","label":"(=) Valor do Documento","valor_fixo":"(=) Valor do Documento","x":155,"y":75,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"valor_documento","tipo":"valor_documento","label":"","variavel":"{{valor_documento}}","x":155,"y":80,"largura":40,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"negrito":true,"borda":true,"alinhamento":"right","formato":"moeda"},
    {"id":"instrucoes_label","tipo":"custom","label":"Instruções","valor_fixo":"Instruções de responsabilidade do Beneficiário.","x":15,"y":90,"largura":140,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"instrucoes","tipo":"instrucoes","label":"","variavel":"{{instrucoes}}","x":15,"y":95,"largura":140,"altura":30,"fonte":"helvetica","tamanho_fonte":8,"borda":true},
    {"id":"desc_label","tipo":"custom","label":"(-) Desconto/Abatimento","valor_fixo":"(-) Desconto/Abatimento","x":155,"y":90,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"desconto_abatimento","tipo":"desconto_abatimento","label":"","variavel":"{{valor_desconto}}","x":155,"y":95,"largura":40,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"alinhamento":"right","formato":"moeda"},
    {"id":"deducoes_label","tipo":"custom","label":"(-) Outras Deduções","valor_fixo":"(-) Outras Deduções","x":155,"y":103,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"outras_deducoes","tipo":"outras_deducoes","label":"","variavel":"{{outras_deducoes}}","x":155,"y":108,"largura":40,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"alinhamento":"right","formato":"moeda"},
    {"id":"mora_label","tipo":"custom","label":"(+) Mora/Multa","valor_fixo":"(+) Mora/Multa","x":155,"y":116,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"mora_multa","tipo":"mora_multa","label":"","variavel":"{{mora_multa}}","x":155,"y":121,"largura":40,"altura":8,"fonte":"helvetica","tamanho_fonte":9,"borda":true,"alinhamento":"right","formato":"moeda"},
    {"id":"pagador_label","tipo":"custom","label":"Pagador","valor_fixo":"Pagador","x":15,"y":127,"largura":140,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"pagador_nome","tipo":"pagador_nome","label":"","variavel":"{{pagador_nome}}","x":15,"y":132,"largura":105,"altura":6,"fonte":"helvetica","tamanho_fonte":9,"negrito":true,"borda":false},
    {"id":"pagador_cnpj","tipo":"pagador_cnpj","label":"","variavel":"{{pagador_cnpj}}","x":120,"y":132,"largura":35,"altura":6,"fonte":"helvetica","tamanho_fonte":9,"borda":false,"formato":"cpf_cnpj"},
    {"id":"pagador_endereco","tipo":"pagador_endereco","label":"","variavel":"{{pagador_endereco}}","x":15,"y":138,"largura":140,"altura":5,"fonte":"helvetica","tamanho_fonte":8,"borda":false},
    {"id":"pagador_cidade","tipo":"pagador_cidade_uf","label":"","variavel":"{{pagador_cidade_uf}}","x":15,"y":143,"largura":100,"altura":5,"fonte":"helvetica","tamanho_fonte":8,"borda":false},
    {"id":"pagador_cep","tipo":"pagador_cep","label":"","variavel":"{{pagador_cep}}","x":115,"y":143,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":8,"borda":false},
    {"id":"valor_cobrado_label","tipo":"custom","label":"(=) Valor Cobrado","valor_fixo":"(=) Valor Cobrado","x":155,"y":129,"largura":40,"altura":5,"fonte":"helvetica","tamanho_fonte":6,"borda":false},
    {"id":"valor_cobrado","tipo":"valor_cobrado","label":"","variavel":"{{valor_cobrado}}","x":155,"y":134,"largura":40,"altura":12,"fonte":"helvetica","tamanho_fonte":10,"negrito":true,"borda":true,"alinhamento":"right","formato":"moeda"},
    {"id":"codigo_barras","tipo":"codigo_barras","label":"Código de Barras","variavel":"{{codigo_barras}}","x":15,"y":150,"largura":180,"altura":20}
  ]'::jsonb,
  'APÓS O VENCIMENTO COBRAR MULTA DE 2% E JUROS DE 1% AO MÊS. PROTESTO AUTOMÁTICO APÓS 5 DIAS DO VENCIMENTO.',
  'boleto_templates',
  'modelos/modelo_padrao_febraban/boleto_padrao.pdf'
)
ON CONFLICT (id) DO UPDATE SET
  campos_mapeados = EXCLUDED.campos_mapeados,
  texto_instrucoes = EXCLUDED.texto_instrucoes,
  tipo_layout = EXCLUDED.tipo_layout,
  padrao = EXCLUDED.padrao,
  updated_at = now();